/**
 * This class is generated by jOOQ
 */
package com.skcraft.plume.common.sql.model.log;


import com.skcraft.plume.common.sql.model.log.tables.Log;
import com.skcraft.plume.common.sql.model.log.tables.LogWorld;
import com.skcraft.plume.common.sql.model.log.tables.records.LogRecord;
import com.skcraft.plume.common.sql.model.log.tables.records.LogWorldRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>log</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<LogRecord, Integer> IDENTITY_LOG = Identities0.IDENTITY_LOG;
	public static final Identity<LogWorldRecord, Short> IDENTITY_LOG_WORLD = Identities0.IDENTITY_LOG_WORLD;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<LogRecord> KEY_LOG_PRIMARY = UniqueKeys0.KEY_LOG_PRIMARY;
	public static final UniqueKey<LogWorldRecord> KEY_LOG_WORLD_PRIMARY = UniqueKeys0.KEY_LOG_WORLD_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<LogRecord, LogWorldRecord> FK_LOG_WORLD_ID = ForeignKeys0.FK_LOG_WORLD_ID;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<LogRecord, Integer> IDENTITY_LOG = createIdentity(Log.LOG, Log.LOG.ID);
		public static Identity<LogWorldRecord, Short> IDENTITY_LOG_WORLD = createIdentity(LogWorld.LOG_WORLD, LogWorld.LOG_WORLD.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<LogRecord> KEY_LOG_PRIMARY = createUniqueKey(Log.LOG, Log.LOG.ID);
		public static final UniqueKey<LogWorldRecord> KEY_LOG_WORLD_PRIMARY = createUniqueKey(LogWorld.LOG_WORLD, LogWorld.LOG_WORLD.ID);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<LogRecord, LogWorldRecord> FK_LOG_WORLD_ID = createForeignKey(com.skcraft.plume.common.sql.model.log.Keys.KEY_LOG_WORLD_PRIMARY, Log.LOG, Log.LOG.WORLD_ID);
	}
}
