/**
 * This class is generated by jOOQ
 */
package com.skcraft.plume.common.sql.model.log;


import javax.annotation.Generated;

import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Log extends SchemaImpl {

	private static final long serialVersionUID = -132632840;

	/**
	 * The reference instance of <code>log</code>
	 */
	public static final Log LOG = new Log();

	/**
	 * No further instances allowed
	 */
	private Log() {
		super("log");
	}
}
