/**
 * This class is generated by jOOQ
 */
package com.skcraft.plume.common.sql.model.log;


import com.skcraft.plume.common.sql.model.log.tables.Log;
import com.skcraft.plume.common.sql.model.log.tables.LogWorld;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in log
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table log.log
	 */
	public static final Log LOG = com.skcraft.plume.common.sql.model.log.tables.Log.LOG;

	/**
	 * The table log.log_world
	 */
	public static final LogWorld LOG_WORLD = com.skcraft.plume.common.sql.model.log.tables.LogWorld.LOG_WORLD;
}
