/**
 * This class is generated by jOOQ
 */
package com.skcraft.plume.common.service.sql.model.data.tables;


import com.skcraft.plume.common.service.sql.model.data.Data;
import com.skcraft.plume.common.service.sql.model.data.Keys;
import com.skcraft.plume.common.service.sql.model.data.tables.records.GroupRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Group extends TableImpl<GroupRecord> {

	private static final long serialVersionUID = 1459060773;

	/**
	 * The reference instance of <code>data.group</code>
	 */
	public static final Group GROUP = new Group();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<GroupRecord> getRecordType() {
		return GroupRecord.class;
	}

	/**
	 * The column <code>data.group.id</code>.
	 */
	public final TableField<GroupRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>data.group.name</code>.
	 */
	public final TableField<GroupRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>data.group.permissions</code>.
	 */
	public final TableField<GroupRecord, String> PERMISSIONS = createField("permissions", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>data.group.auto_join</code>.
	 */
	public final TableField<GroupRecord, Byte> AUTO_JOIN = createField("auto_join", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>data.group</code> table reference
	 */
	public Group() {
		this("group", null);
	}

	/**
	 * Create an aliased <code>data.group</code> table reference
	 */
	public Group(String alias) {
		this(alias, GROUP);
	}

	private Group(String alias, Table<GroupRecord> aliased) {
		this(alias, aliased, null);
	}

	private Group(String alias, Table<GroupRecord> aliased, Field<?>[] parameters) {
		super(alias, Data.DATA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<GroupRecord, Integer> getIdentity() {
		return Keys.IDENTITY_GROUP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<GroupRecord> getPrimaryKey() {
		return Keys.KEY_GROUP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<GroupRecord>> getKeys() {
		return Arrays.<UniqueKey<GroupRecord>>asList(Keys.KEY_GROUP_PRIMARY, Keys.KEY_GROUP_NAME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Group as(String alias) {
		return new Group(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Group rename(String name) {
		return new Group(name, null);
	}
}
