/**
 * This class is generated by jOOQ
 */
package com.skcraft.plume.common.service.sql.model.data;


import com.skcraft.plume.common.service.sql.model.data.tables.Ban;
import com.skcraft.plume.common.service.sql.model.data.tables.Claim;
import com.skcraft.plume.common.service.sql.model.data.tables.Group;
import com.skcraft.plume.common.service.sql.model.data.tables.GroupParent;
import com.skcraft.plume.common.service.sql.model.data.tables.Party;
import com.skcraft.plume.common.service.sql.model.data.tables.PartyMember;
import com.skcraft.plume.common.service.sql.model.data.tables.User;
import com.skcraft.plume.common.service.sql.model.data.tables.UserGroup;
import com.skcraft.plume.common.service.sql.model.data.tables.UserId;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Data extends SchemaImpl {

	private static final long serialVersionUID = 1921184454;

	/**
	 * The reference instance of <code>data</code>
	 */
	public static final Data DATA = new Data();

	/**
	 * No further instances allowed
	 */
	private Data() {
		super("data");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Ban.BAN,
			Claim.CLAIM,
			Group.GROUP,
			GroupParent.GROUP_PARENT,
			Party.PARTY,
			PartyMember.PARTY_MEMBER,
			User.USER,
			UserGroup.USER_GROUP,
			UserId.USER_ID);
	}
}
