/**
 * This class is generated by jOOQ
 */
package com.skcraft.plume.common.service.sql.model.data;


import com.skcraft.plume.common.service.sql.model.data.tables.Ban;
import com.skcraft.plume.common.service.sql.model.data.tables.Claim;
import com.skcraft.plume.common.service.sql.model.data.tables.Group;
import com.skcraft.plume.common.service.sql.model.data.tables.GroupParent;
import com.skcraft.plume.common.service.sql.model.data.tables.Party;
import com.skcraft.plume.common.service.sql.model.data.tables.PartyMember;
import com.skcraft.plume.common.service.sql.model.data.tables.User;
import com.skcraft.plume.common.service.sql.model.data.tables.UserGroup;
import com.skcraft.plume.common.service.sql.model.data.tables.UserId;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in data
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table data.ban
	 */
	public static final Ban BAN = com.skcraft.plume.common.service.sql.model.data.tables.Ban.BAN;

	/**
	 * The table data.claim
	 */
	public static final Claim CLAIM = com.skcraft.plume.common.service.sql.model.data.tables.Claim.CLAIM;

	/**
	 * The table data.group
	 */
	public static final Group GROUP = com.skcraft.plume.common.service.sql.model.data.tables.Group.GROUP;

	/**
	 * The table data.group_parent
	 */
	public static final GroupParent GROUP_PARENT = com.skcraft.plume.common.service.sql.model.data.tables.GroupParent.GROUP_PARENT;

	/**
	 * The table data.party
	 */
	public static final Party PARTY = com.skcraft.plume.common.service.sql.model.data.tables.Party.PARTY;

	/**
	 * The table data.party_member
	 */
	public static final PartyMember PARTY_MEMBER = com.skcraft.plume.common.service.sql.model.data.tables.PartyMember.PARTY_MEMBER;

	/**
	 * The table data.user
	 */
	public static final User USER = com.skcraft.plume.common.service.sql.model.data.tables.User.USER;

	/**
	 * The table data.user_group
	 */
	public static final UserGroup USER_GROUP = com.skcraft.plume.common.service.sql.model.data.tables.UserGroup.USER_GROUP;

	/**
	 * The table data.user_id
	 */
	public static final UserId USER_ID = com.skcraft.plume.common.service.sql.model.data.tables.UserId.USER_ID;
}
