/**
 * This class is generated by jOOQ
 */
package com.skcraft.plume.common.service.sql.model.data.tables.records;


import com.skcraft.plume.common.service.sql.model.data.tables.GroupParent;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupParentRecord extends UpdatableRecordImpl<GroupParentRecord> implements Record2<Integer, Integer> {

	private static final long serialVersionUID = 1149231674;

	/**
	 * Setter for <code>data.group_parent.parent_id</code>.
	 */
	public void setParentId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>data.group_parent.parent_id</code>.
	 */
	public Integer getParentId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>data.group_parent.group_id</code>.
	 */
	public void setGroupId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>data.group_parent.group_id</code>.
	 */
	public Integer getGroupId() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Integer, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return GroupParent.GROUP_PARENT.PARENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return GroupParent.GROUP_PARENT.GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getParentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupParentRecord value1(Integer value) {
		setParentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupParentRecord value2(Integer value) {
		setGroupId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupParentRecord values(Integer value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GroupParentRecord
	 */
	public GroupParentRecord() {
		super(GroupParent.GROUP_PARENT);
	}

	/**
	 * Create a detached, initialised GroupParentRecord
	 */
	public GroupParentRecord(Integer parentId, Integer groupId) {
		super(GroupParent.GROUP_PARENT);

		setValue(0, parentId);
		setValue(1, groupId);
	}
}
