/**
 * This class is generated by jOOQ
 */
package com.skcraft.plume.common.service.sql.model.log;


import com.skcraft.plume.common.service.sql.model.log.tables.LogWorld;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Log extends SchemaImpl {

	private static final long serialVersionUID = 307769737;

	/**
	 * The reference instance of <code>log</code>
	 */
	public static final Log LOG = new Log();

	/**
	 * No further instances allowed
	 */
	private Log() {
		super("log");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			com.skcraft.plume.common.service.sql.model.log.tables.Log.LOG,
			LogWorld.LOG_WORLD);
	}
}
